AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resize video with ffmpeg

Parameters:
  SourceBucketName:
    Type: String
    Default: 'video-converter-example-source'
  OutputBucketName:
    Type: String
    Default: 'video-converter-example-dest'

Resources:
  ## S3 buckets
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SourceBucketName}-${AWS::AccountId}-${AWS::Region}'
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${OutputBucketName}-${AWS::AccountId}-${AWS::Region}'

  ## Lambda layers
  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Static FFmpeg and FFprobe binaries for Linux arm64
      ContentUri: ffmpegLayer/
      # Remove old layer versions when the stack is updated or deleted
      RetentionPolicy: Delete
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - nodejs24.x
    Metadata:
      BuildMethod: makefile

  ## Lambda functions
  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resizeFunction/
      Handler: app.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Timeout: 900
      MemorySize: 10240
      EphemeralStorage:
        Size: 10240      
      Layers:
        - !Ref FfmpegLayer
      Environment:
        Variables:
          OutputBucketName: !Sub '${OutputBucketName}-${AWS::AccountId}-${AWS::Region}'
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${SourceBucketName}-${AWS::AccountId}-${AWS::Region}'
        - S3WritePolicy:
            BucketName: !Sub '${OutputBucketName}-${AWS::AccountId}-${AWS::Region}'
      Events:
        CreatedEvent:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.mp4'
