AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3-to-EventBridge Integration 1 - Simple Invoke

Parameters:
  SourceBucketName:
    Type: String
    Default: patterns-s3-eventbridge-src-bucket

Resources:
  # S3 Bucket - sends all object events to the default EventBridge bus
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SourceBucketName}-${AWS::AccountId}-${AWS::Region}'
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  ### This section configures the consuming Lambda function ###

  # Lambda function
  EventConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eventConsumer/
      Handler: app.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64

  # EventBridge rule - invokes EventConsumerFunction 
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventRule
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref SourceBucket
      Targets:
        - Arn: !GetAtt EventConsumerFunction.Arn
          Id: EventConsumerFunctionTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EventConsumerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn