AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3-to-EventBridge Integration 4 - Multiple Buckets, Multiple consumers

Parameters:
  MultiBucketName:
    Type: String
    Default: patterns-s3-eventbridge-multi2

Resources:
  # S3 Buckets - each sends all object events to the default EventBridge bus
  MultiBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MultiBucketName}-${AWS::AccountId}-${AWS::Region}-1
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  MultiBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MultiBucketName}-${AWS::AccountId}-${AWS::Region}-2
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  MultiBucket3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MultiBucketName}-${AWS::AccountId}-${AWS::Region}-3
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  ### This section configures the consuming Lambda function ###

  # Lambda function
  EventConsumerFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eventConsumer1/
      Handler: app.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64

  EventConsumerFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eventConsumer2/
      Handler: app.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64

  EventConsumerFunction3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eventConsumer3/
      Handler: app.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64

  # EventBridge rule - invokes EventConsumerFunction 
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventRule
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref MultiBucket1
              - !Ref MultiBucket2
              - !Ref MultiBucket3
      Targets:
        - Arn: !GetAtt EventConsumerFunction1.Arn
          Id: EventConsumerFunctionTarget1
        - Arn: !GetAtt EventConsumerFunction2.Arn
          Id: EventConsumerFunctionTarget2
        - Arn: !GetAtt EventConsumerFunction3.Arn
          Id: EventConsumerFunctionTarget3

  PermissionForEventsToInvokeLambda1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EventConsumerFunction1
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn

  PermissionForEventsToInvokeLambda2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EventConsumerFunction2
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn

  PermissionForEventsToInvokeLambda3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EventConsumerFunction3
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn